protected/extensions/lily/controllers/UserController.php
<?php

/**
 * UserController class file.
 *
 * @author George Agapov <george.agapov@gmail.com>
 * @link https://github.com/georgeee/yii-lily
 * @license http://www.opensource.org/licenses/bsd-license.php
 */

/**
 * UserController is a controller class, which manages with user login/logout/activate/edit/list/view actions.
 *
 * @package application.modules.lily.controllers
 */
class UserController extends Controller {

    /**
     * @var string the name of the default action
     */
    public $defaultAction = 'view';

    /**
     * Declares filters for the controller
     * @return array filters
     */
    public function filters() {
        return array(
            'accessControl'
        );
    }

    /**
     * Declares access rules for the controller
     * @return array access rules
     */
    public function accessRules() {
        return array(
            array('deny',
                'actions' => array('logout'),
                'users' => array('?'),
            ),
            array('deny',
                'actions' => array('login', 'onetime'),
                'users' => array('@'),
            ),
        );
    }

    /**
     * Login action
     * @param string $service Service, which is being authenticated
     * @param boolean $rememberMe Whether to remember user
     * @throws LException
     */
    public function actionLogin($service = null, $rememberMe = false) {
        $id_prefix = 'LAuthWidget-form-';
        if (isset($_POST['ajax']) && substr($_POST['ajax'], 0, strlen($id_prefix)) == $id_prefix) {
            $model = new LLoginForm;
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        $model_new = false;
        $services = LilyModule::instance()->services;
        if ($service != null) {
            $_services = $services;
            unset($_services['email']);
            $model = new LLoginForm('', array_keys($_services));
            $model->service = $service;
            $model->rememberMe = $rememberMe;
        } else {
            $model = new LLoginForm('', array_keys($services));
            if (isset($_POST['LLoginForm'])) {
                $model->attributes = $_POST['LLoginForm'];
                //Special behaviour for cases, when JS isn't enabled
                if ($model->validate() && $model->service != 'email') {
                    $this->redirect(array('', 'service' => $model->service, 'rememberMe' => $model->rememberMe));
                }
            }else
                $model_new = true;
        }

        if (!$model_new && $model->validate() && isset($model->service)) {
            $authIdentity = Yii::app()->eauth->getIdentity($model->service);
            /* @var $authIdentity LEmailService */
            $authIdentity->redirectUrl = Yii::app()->user->returnUrl;
            $authIdentity->cancelUrl = $this->createAbsoluteUrl('user/login');
            if ($model->service == 'email') {
                $authIdentity->email = $model->email;
                $authIdentity->password = $model->password;
                $authIdentity->rememberMe = $model->rememberMe;
            }
            if ($authIdentity->authenticate()) {
                if ($model->service == 'email' && $authIdentity->errorCode == LEmailService::ERROR_INFORMATION_MAIL_FAILED)
                    Yii::app()->user->setFlash('lily.login.error', LilyModule::t("Your account was created, but it failed to send you email with account information."));

                $identity = new LUserIdentity($authIdentity);
                //Authentication succeed
                if ($identity->authenticate()) {
                    /* @var $user LUser */
                    $user = (isset($identity->user) ? $identity->user : $identity->session->user);
                    if ($user->state == LUser::BANNED_STATE && Yii::app()->authManager->checkAccess('unbanUser', $user->uid, array('uid' => $user->uid))) {
                        $user->state = LUser::ACTIVE_STATE;
                        if (!$user->save())
                            throw new CDbException("failed to save user");
                    }
                    if ($user->state == LUser::BANNED_STATE) {
                        Yii::app()->user->setFlash('lily.login.error', LilyModule::t("Your account was put under ban. Please contact to site administrator for details."));
                    } else {
                        $result = Yii::app()->user->login($identity, $model->rememberMe ? LilyModule::instance()->sessionTimeout : 0);
                        if ($result)
                            Yii::app()->user->setFlash('lily.login.success', LilyModule::t('You were successfully logged in.'));
                        else
                            throw new LException("login() returned false");
                    }
                    //Special redirect to fire popup window closing
                    $authIdentity->redirect();
                } else {/* $identity->authenticate() returns true only when $authIdentity returns true, so this else will never be achieved */
                }
            }
            //Auth failed, close popup and redirect to $authIdentity->cancelUrl
            if ($model->service == 'email') {
                switch ($authIdentity->errorCode) {
                    case LEmailService::ERROR_ACTIVATION_MAIL_SENT:
                        Yii::app()->user->setFlash('lily.login.success', LilyModule::t("Activation e-mail sent."));
                        break;
                    case LEmailService::ERROR_ACTIVATION_MAIL_FAILED:
                        Yii::app()->user->setFlash('lily.login.error', LilyModule::t("Failed to send account activation email."));
                        break;
                    case LEmailService::ERROR_AUTH_FAILED:
                        Yii::app()->user->setFlash('lily.login.error', LilyModule::t("Failed to authenticate (email-password mismatch)."));
                        break;
                    case LEmailService::ERROR_NOT_REGISTERED:
                        Yii::app()->user->setFlash('lily.login.error', LilyModule::t("Account with given e-mail is not registered. You have to pass registration."));
                        $authIdentity->cancelUrl = $this->createUrl('register', array('email' => $authIdentity->email));
                        break;
                }
            } else {
                Yii::app()->user->setFlash('lily.login.error', LilyModule::t('Failed to authenticate.'));
            }
            $authIdentity->cancel();
        }
        $this->render('login', array('model' => $model, 'services' => $services));
    }

    /**
     * Register action 
     */
    public function actionRegister() {
        if (isset($_POST['ajax']) && $_POST['ajax'] == 'LRegisterForm-form') {
            $model = new LRegisterForm;
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        $model = new LRegisterForm;
        if (isset($_POST['LRegisterForm'])) {
            $model->attributes = $_POST['LRegisterForm'];
            if ($model->validate()) {
                $email = $model->email;
                $password = $model->password;
                $authIdentity = new LEmailService;
                $authIdentity->email = $email;
                $authIdentity->password = $password;
                $authIdentity->user = Yii::app()->user->isGuest ? null : LilyModule::instance()->user;
                $authIdentity->rememberMe = $model->rememberMe;
                if ($authIdentity->authenticate(true)) {
                    if (LilyModule::instance()->accountManager->loginAfterRegistration && Yii::app()->user->isGuest) {
                        $identity = new LUserIdentity($authIdentity);
                        $identity->authenticate();
                        $result = Yii::app()->user->login($identity, $model->rememberMe ? LilyModule::instance()->sessionTimeout : 0);

                        if ($result)
                            Yii::app()->user->setFlash('lily.login.success', LilyModule::t('You were successfully logged in.'));
                        else
                            throw new LException("login() returned false");
                    }
                    $authIdentity->redirect(Yii::app()->user->isGuest ? Yii::app()->homeUrl : $this->createUrl('view'));
                } else {
                    switch ($authIdentity->errorCode) {
                        case LEmailService::ERROR_ACTIVATION_MAIL_SENT:
                            Yii::app()->user->setFlash('lily.login.success', LilyModule::t("Activation e-mail sent."));
                            break;
                        case LEmailService::ERROR_ACTIVATION_MAIL_FAILED:
                            Yii::app()->user->setFlash('lily.login.error', LilyModule::t("Failed to send account activation email."));
                            break;
                        case LEmailService::ERROR_INFORMATION_MAIL_FAILED:
                            Yii::app()->user->setFlash('lily.login.error', LilyModule::t("Your account was created, but it failed to send you email with account information."));
                            break;
                    }
                }
                //Special redirect to fire popup window closing
                $authIdentity->cancel();
            }
        } else if (isset($_GET['email']))
            $model->email = $_GET['email'];
        $this->render('register', array('model' => $model));
    }

    /**
     * Activate action
     * @param $code Activation code
     */
    public function actionActivate($code) {
        $_code = LEmailAccountActivation::model()->findByAttributes(array('code' => $code));
        if (isset($_code)) {
            $rememberMe = $_code->rememberMe;
        }
        $account = LilyModule::instance()->accountManager->performActivation($code);
        /* $errorCode:
         * <ul>
         * <li>1 - failed to find code DB record</li>

protected/extensions/lily/views/user/authForm.php
<div class="form">
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => $id,
        'htmlOptions' => array('class' => 'authForm'),
        'action' => $action,
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        ),)
    );
    
    Yii::app()->clientScript->registerScript('lily-init'.$id, '$("#'.$id.'").lily();');
    ?>
    <h2>Choose your auth method:</h2>

    <div class="authMethodSwitcherDiv">
        <ul class="authMethodSwitcher">
            <?php foreach ($services as $service => $options) { ?>
                <li class="authMethod <?php echo $options->id; ?>" service="<?php echo $options->id; ?>">
                    <a class="authMethodLink" href="#">
                        <div class="authMethodIcon"><i></i></div>
                        <div class="authMethodTitle"><?php echo $options->title; ?></div>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
    <div class="authMethodSelectDiv row">
        <?php
        $data = $options = array();
        foreach ($services as $service => $opts) {
            $data[$service] = $opts->title;
            $options[$service] = array('class' => 'option_' . $service);
        }
        echo $form->dropDownList($model, 'service', $data, array('class' => 'authMethodSelect', 'options' => $options));
        ?>

    </div>
    <div class="eauthHandlers">
        <?php
        foreach ($services as $name => $service) {
            if ($name == 'email')
                continue;
            echo '<div class="auth-service ' . $service->id . '">'
            . CHtml::link('-', array($action, 'service' => $name), array('class' => 'auth-link ' . $service->id,))
            . '</div>';
        }
        ?>
    </div>
    <div class="formDiv">
        <?php if (isset($services['email'])) { ?>
            <div class="emailFieldsDiv">
                <p class="note emailFieldHint"><?php echo LilyModule::t('Use fields Email, Password when method "E-mail" was selected'); ?></p>                

                <?php if (LilyModule::instance()->accountManager->registerEmail) { ?>
                    <p class="note"><?php echo LilyModule::t('If you\'re not yet registered, just fill in E-mail and password fields with your e-mail address and a password you want to use. You\'ll be automaticaly registrated.'); ?></p>
                <?php } else { ?>
                    <p class="note"><?php echo LilyModule::t('If you\'re not yet registered, just go to {registrationPageLink} and pass the registration. Or you can choose another authentication method.', array('{registrationPageLink}' => CHtml::link(LilyModule::t("registration page"), array("user/register")))); ?></p>
                <?php } ?>
                    

                <p class="note"><?php echo LilyModule::t('If you forgot your password, you can restore it using {restorePageLink}', array('{restorePageLink}' => CHtml::link(LilyModule::t('this page'), Yii::app()->createUrl('/'.LilyModule::route('account/restore'))))); ?>.</p>

                <div class="row">
                    <?php echo $form->labelEx($model, 'email'); ?>
                    <?php echo $form->textField($model, 'email'); ?>
                    <?php echo $form->error($model, 'email'); ?>
                </div>

                <div class="row">
                    <?php echo $form->labelEx($model, 'password'); ?>
                    <?php echo $form->passwordField($model, 'password'); ?>
                    <?php echo $form->error($model, 'password'); ?>
                    <?php if (LilyModule::instance()->accountManager->registerEmail) { ?>
                        <p class="hint">
                            <?php echo LilyModule::t('In password you can use lowercase and uppercase latin letters, characters (excluding quotes) {passwordSymbols} and simple whitespace.
        <br /> Password\'s length must be from 8 to 32 characters.', array('{passwordSymbols}' => '&quot;-.,;=+~/\[]{}!@#$%^*&amp;()_|&quot;')); ?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
        <div class="row rememberMeFieldDiv" <?php if (!$showRememberMe) { ?>style="display:none;"<?php } ?>>
            <?php echo $form->checkBox($model, 'rememberMe', array('class' => 'authMethodRememberMe')); ?>
            <?php echo $form->label($model, 'rememberMe', array('class' => 'authMethodRememberMeLabel')); ?>
            <?php echo $form->error($model, 'rememberMe'); ?>
        </div>
        <div class="row buttons">
            <?php echo CHtml::submitButton($submitLabel, array('class' => 'submitButton')); ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>
</div><!-- form -->

protected/extensions/lily/views/user/init.php
<?php
/* @var $this Controller*/
$this->pageTitle = LilyModule::t('{appName} - User initialization', array('{appName}' => Yii::app()->name));
$this->breadcrumbs = array(
    LilyModule::t('User initialization')
);
?><h1><?php echo LilyModule::t('Account initialization');?></h1>
<?php
switch ($action) {
    case 'start':
        ?>
        <div>
            <?php echo LilyModule::t('Please fill in next few forms in order to initialize your account.');?>
            <br/> <?php echo CHtml::link(LilyModule::t('Start'), $this->createUrl('', array('action' => 'next'))); ?>
        </div>
        <?php
        break;
    case 'finish':
        ?>
        <div>
            <?php echo LilyModule::t('Account was successfully initialized.'); ?>
            <br/> <?php echo CHtml::link(LilyModule::t('Finish'), $this->createUrl('', array('action' => 'next'))); ?>
        </div>
        <?php
        break;
}

protected/extensions/lily/views/user/list.php
<?php
/* @var $this Controller */
$this->pageTitle = LilyModule::t('{appName} - Users', array('{appName}' => Yii::app()->name));
$this->breadcrumbs = array(
    LilyModule::t('Users')
);
?><h1><?php echo LilyModule::t('Users'); ?></h1>
<form id="userListOptions" action="">
    <?php if (Yii::app()->user->checkAccess('viewDeletedUser') || Yii::app()->user->checkAccess('viewUser')) { ?>
        <input type="checkbox" id="hideDeletedCheckbox" value="0" name="showDeleted" <?php echo $showDeleted ? "" : "checked"; ?>>
        <label for="hideDeletedCheckbox"><?php echo LilyModule::t("hide deleted users"); ?> </label>
        <br />
    <?php } ?>
    <?php if (Yii::app()->user->checkAccess('viewBannedUser') || Yii::app()->user->checkAccess('viewUser')) { ?>
        <input type="checkbox" id="hideBannedCheckbox" value="0" name="showBanned" <?php echo $showBanned ? "" : "checked"; ?>>
        <label for="hideBannedCheckbox"> <?php echo LilyModule::t("hide banned users"); ?> </label>
        <br />
    <?php } ?>
    <?php if (Yii::app()->user->checkAccess('viewAppendedUser') || Yii::app()->user->checkAccess('viewUser')) { ?>
        <input type="checkbox" id="hideAppendedCheckbox" value="0" name="showAppended" <?php echo $showAppended ? "" : "checked"; ?>>
        <label for="hideAppendedCheckbox"> <?php echo LilyModule::t("hide appended users"); ?></label> 
        <br />
    <?php } ?>
    <?php if (Yii::app()->user->checkAccess('viewActiveUser') || Yii::app()->user->checkAccess('viewUser')) { ?>
        <input type="checkbox" id="hideActiveCheckbox" value="0" name="showActive" <?php echo $showActive ? "" : "checked"; ?>>
        <label for="hideActiveCheckbox"> <?php echo LilyModule::t("hide active users"); ?></label> 
        <br />
    <?php } ?>
    <input type="submit" value="<?php echo LilyModule::t('Reload user list'); ?>">
</form>

<?php

$columns = array(
    array('name' => 'uid'),
    array(
        'name' => 'name',
        'type' => 'raw',
        'value' => 'CHtml::link(CHtml::encode($data->name),array("user/view","uid"=>$data->uid))',
    ),
    array(
        'header' => LilyModule::t('Accounts'),
        'label' => LilyModule::t('Account list'),
        'class' => 'CLinkColumn',
        'urlExpression' => 'Yii::app()->urlManager->createUrl("' . LilyModule::instance()->route('account/list') . '", array(\'uid\'=>$data->uid))',
    ),
);


$columns[] = array(
    'name' => 'state',
    'type' => 'raw',
    'value' => array('LUser', 'getStateLabel'),
);

$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $dataProvider,
    'columns' => $columns,
));
?>

protected/extensions/lily/views/user/login.php
<?php
/* @var $this Controller*/
$this->pageTitle = LilyModule::t('{appName} - Login', array('{appName}' => Yii::app()->name));
$this->breadcrumbs = array(
    LilyModule::t('Login')
);
?><h1><?php echo LilyModule::t('Login');?></h1>
<p><?php echo LilyModule::t('Please fill out the following form with your login credentials:');?></p>
<?php $this->widget('LAuthWidget', array('model' => $model, 'services' => $services, 'showRememberMe' => true, 'submitLabel' => LilyModule::t('Login'), 'action' => '')); ?>

protected/extensions/lily/views/user/register.php
<?php
/* @var $this Controller*/
$this->pageTitle = LilyModule::t('{appName} - E-mail registration', array('{appName}' => Yii::app()->name));
$this->breadcrumbs = array(
    LilyModule::t('E-mail registration')
);
?><h1><?php echo LilyModule::t('E-mail registration');?></h1>
<p><?php echo LilyModule::t('Please fill out the following form:');?></p>
<div class="form">
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => "LRegisterForm-form",
        'htmlOptions' => array('class'=>'regForm'),
        'action'=>'',
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        ),)
    );
    ?>
    <div class="formDiv">
            <div class="emailFieldsDiv">              

                <p class="note"><?php echo LilyModule::t('If you forgot your password, you can restore it using {restorePageLink}', array('{restorePageLink}' => CHtml::link(LilyModule::t('this page'), Yii::app()->createUrl('/'.LilyModule::route('account/restore'))))); ?>.</p>

                <div class="row">
                    <?php echo $form->labelEx($model, 'email'); ?>
                    <?php echo $form->textField($model, 'email'); ?>
                    <?php echo $form->error($model, 'email'); ?>
                </div>

                <div class="row">
                    <?php echo $form->labelEx($model, 'password'); ?>
                    <?php echo $form->passwordField($model, 'password'); ?>
                    <?php echo $form->error($model, 'password'); ?>
                    <p class="hint">
                            <?php echo LilyModule::t('In password you can use lowercase and uppercase latin letters, characters (excluding quotes) {passwordSymbols} and simple whitespace.
        <br /> Password\'s length must be from 8 to 32 characters.', array('{passwordSymbols}' => '&quot;-.,;=+~/\[]{}!@#$%^*&amp;()_|&quot;')); ?>
                        </p>
                </div>
                <div class="row">
                    <?php echo $form->labelEx($model, 'passwordRepeat'); ?>
                    <?php echo $form->passwordField($model, 'passwordRepeat'); ?>
                    <?php echo $form->error($model, 'passwordRepeat'); ?>
                    
                </div>
            </div>
        <?php if(LilyModule::instance()->accountManager->loginAfterRegistration){ ?>
        <div class="row rememberMeFieldDiv">
            <?php echo $form->checkBox($model, 'rememberMe', array('class' => 'authMethodRememberMe')); ?>
            <?php echo $form->label($model, 'rememberMe', array('class' => 'authMethodRememberMeLabel')); ?>
            <?php echo $form->error($model, 'rememberMe'); ?>
        </div>
        <?php } ?>
        <div class="row buttons">
            <?php echo CHtml::submitButton(LilyModule::t("Register me"), array('class'=>'submitButton')); ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>
</div><!-- form -->

protected/extensions/lily/views/user/switch_state.php
<?php
/* @var $this Controller */
switch ($mode) {
    case LUser::ACTIVE_STATE:
        $this->pageTitle = LilyModule::t('{appName} - Activate user', array('{appName}' => Yii::app()->name));
        $this->breadcrumbs = array(
            LilyModule::t('User') => $this->createUrl('user/view', array('uid' => $user->uid)),
            LilyModule::t('Activate')
        );
        ?><h1><?php echo LilyModule::t('Activate user'); ?></h1><?php
        break;
    case LUser::DELETED_STATE:
        $this->pageTitle = LilyModule::t('{appName} - Delete user', array('{appName}' => Yii::app()->name));
        $this->breadcrumbs = array(
            LilyModule::t('User') => $this->createUrl('user/view', array('uid' => $user->uid)),
            LilyModule::t('Delete')
        );
        ?><h1><?php echo LilyModule::t('Delete user'); ?></h1><?php
        break;
    case LUser::BANNED_STATE:
        $this->pageTitle = LilyModule::t('{appName} - Ban user', array('{appName}' => Yii::app()->name));
        $this->breadcrumbs = array(
            LilyModule::t('User') => $this->createUrl('user/view', array('uid' => $user->uid)),
            LilyModule::t('Ban')
        );
        ?><h1><?php echo LilyModule::t('Ban user'); ?></h1><?php
        break;
}
?>
<form action="" method="POST">
    <p>
        <?php
        /* @var $this UserController */
        switch ($mode) {
            case LUser::ACTIVE_STATE: $txt = LilyModule::t(!$self ? "Do you really want to activate user {user} account?" : "Do you really want to activate your account?", array('{user}' => $user->name));
                break;
            case LUser::DELETED_STATE: $txt = LilyModule::t(!$self ? "Do you really want to delete user {user} account?" : "Do you really want to delete your account?", array('{user}' => $user->name));
                break;
            case LUser::BANNED_STATE: $txt = LilyModule::t("Do you really want to ban user {user} account?", array('{user}' => $user->name));
                break;
        }
        echo CHtml::encode($txt);
        ?>
    </p>
    <input type="hidden" name="approved" value="1" />
    <div>
        <a href="<?php
        echo $this->createUrl(($user->id == Yii::app()->user->id && $user->state == LUser::DELETED_STATE) ? 'logout' : 'view', array('uid' => $user->uid));
        ?>"><?php echo CHtml::encode(LilyModule::t("Cancel")); ?></a>
        <input type="submit" value=" <?php
        switch ($mode) {
            case LUser::ACTIVE_STATE: $txt = LilyModule::t(!$self ? "Activate user" : "Activate my user account");
                break;
            case LUser::DELETED_STATE: $txt = LilyModule::t(!$self ? "Delete user" : "Delete my user account");
                break;
            case LUser::BANNED_STATE: $txt = LilyModule::t("Ban user");
                break;
        }
        echo CHtml::encode($txt);
        ?> " />
    </div>
</form>

protected/extensions/lily/views/user/view.php
<?php
/* @var $this Controller*/
$this->pageTitle = LilyModule::t('{appName} - User', array('{appName}' => Yii::app()->name));
$this->breadcrumbs = array(
    LilyModule::t('User {userName}', array('{userName}'=>$user->name))
);
?><h1><?php echo LilyModule::t('User {userName}', array('{userName}'=>$user->name));?></h1>

<?php

/* @var $user LUser */

$attrs = array('uid', 'name');

$attrs[] = array(
    'name' => 'state',
    'type' => 'raw',
    'value' => LUser::getStateLabel($user),
);

$attrs[] = array(
    'name' => 'inited',
    'type' => 'raw',
    'value' => LUser::getInitedLabel($user),
);
if (Yii::app()->user->checkAccess('listAccounts', array('uid' => $user->uid))) {
    $attrs[] = array(
        'label' => LilyModule::t('Accounts'),
        'type' => 'raw',
        'value' => CHtml::link(LilyModule::t("Go to account list"), array('/'.LilyModule::route("account/list"), 'uid' => $user->uid)),
    );
    $attrs[] = array(
        'type' => 'raw',
        'value' => $this->widget('zii.widgets.grid.CGridView', array(
            'dataProvider' => new CActiveDataProvider('LAccount', array(
                'criteria' => array(
                    'condition' => 'uid=:uid AND hidden=0',
                    'params' => array(':uid' => $user->uid),
                    'order' => 'created ASC',
                ),
            )),
            'enablePagination' => false,
            'summaryText' => '',
            'columns' => array(
                array(
                    'name' => 'service',
                    'value' => '$data->serviceName',
                ),
                array(
                    'name' => 'id',
                    'value' => '$data->displayId',
                ),
                array(
                    'name' => 'created',
                    'value' => 'Yii::app()->dateFormatter->formatDateTime($data->created)',
                ),
            ),
                ), true)
            ,
    );
}
if ($user->state <= LUser::ACTIVE_STATE) {
    $value = '';
    if ($user->state != LUser::ACTIVE_STATE && (
            ($user->state == LUser::DELETED_STATE && Yii::app()->user->checkAccess('restoreUser', array('uid' => $user->uid)))
            || ($user->state == LUser::BANNED_STATE && Yii::app()->user->checkAccess('unbanUser', array('uid' => $user->uid)))
            ))
        $value.= '<li>' . CHtml::link(LilyModule::t("Activate user"), $this->createUrl("user/switch_state", array('uid' => $user->uid, 'mode' => LUser::ACTIVE_STATE))) . '</li>';
    if ($user->state != LUser::DELETED_STATE && (
            ($user->state == LUser::ACTIVE_STATE && Yii::app()->user->checkAccess('deleteUser', array('uid' => $user->uid)))
            || ($user->state == LUser::BANNED_STATE && Yii::app()->user->checkAccess('unbanUser', array('uid' => $user->uid)) && Yii::app()->user->checkAccess('deleteUser', array('uid' => $user->uid)))
            ))
        $value .= '<li>' . CHtml::link(LilyModule::t("Delete user"), $this->createUrl("user/switch_state", array('uid' => $user->uid, 'mode' => LUser::DELETED_STATE))) . '</li>';
    if ($user->state != LUser::BANNED_STATE && !Yii::app()->authManager->checkAccess('unbanUser', $user->uid, array('uid' => $user->uid)) && (
            ($user->state == LUser::ACTIVE_STATE && Yii::app()->user->checkAccess('banUser', array('uid' => $user->uid)))
            || ($user->state == LUser::DELETED_STATE && Yii::app()->user->checkAccess('restoreUser', array('uid' => $user->uid)) && Yii::app()->user->checkAccess('banUser', array('uid' => $user->uid)))
            ))
        $value.= '<li>' . CHtml::link(LilyModule::t("Ban user"), $this->createUrl("user/switch_state", array('uid' => $user->uid, 'mode' => LUser::BANNED_STATE))) . '</li>';
    if(!empty($value))
    $attrs[] = array(
        'type' => 'raw',
        'label' => LilyModule::t('Actions'),
        'value' => '<ul>' . $value . '</ul>'
    );
}
$this->widget('zii.widgets.CDetailView', array(
    'data' => $user,
    'itemCssClass' => array(),
    'attributes' => $attrs,
));